<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;

class DataVisualizationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert the DataVisualization course
        $courseId = DB::table('courses')->insertGetId([
            'slug' => Str::slug('DataVisualization'),
            'course_name' => 'DataVisualization',
            'description' => 'DataVisualization Course Description',
            'difficulty' => 'Beginner',
            'category' => 'Programming',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        // Define a topic for DataVisualization course
        $topics = [
            ['course_id' => $courseId, 'name' => 'Introduction'],
        ];

        foreach ($topics as $topic) {
            $topicId = DB::table('topics')->insertGetId([
                'course_id' => $topic['course_id'],
                'name' => $topic['name'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);

            // Define questions for the Introduction topic
            $questions = [
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the primary purpose of data visualization?',
                    'answer' => 'To communicate information clearly and efficiently',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is commonly defined as the communicating of information using graphical means?',
                    'answer' => 'Visualisation',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What idiom implies that pictures can convey information more efficiently than a page of words?',
                    'answer' => 'A picture is worth a thousand words',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What idiom implies that pictures can convey information more efficiently than a page of words?',
                    'answer' => 'A picture is worth a thousand words',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the main difference between Visualisation and Computer Graphics?',
                    'answer' => 'Visualisation uses graphics to convey information via imagery focusing on data properties like spatial positioning and physical measures, while Computer Graphics is an end tool mainly for display and refinement.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How have representations in Biomolecular Chemistry evolved over time?',
                    'answer' => 'They evolved from using sticks and balls to represent molecules to more realistic models with computer-generated graphics and information visualisations like scatterplots.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What distinguishes Scientific Data Visualisation from Information Visualisation?',
                    'answer' => 'Scientific Data Visualisation is often concerned with 3D volume and intense memory handling, whereas Information Visualisation focuses on displaying large sets of data points, requiring efficient data access.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why is the computational task of displaying a volume image made up of 1 Billion Points considered intense?',
                    'answer' => 'It requires intensive memory handling and large scale computations for imaging the 3D volume, making the process computationally demanding.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does handling data in a scatterplot displaying 1 Billion patients\' data points differ from processing a volume image of 1 Billion Points?',
                    'answer' => 'Handling data in a scatterplot is more focused on file reads and data accesses from a database, which is computationally less arduous than processing a 3D volume image.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What initial steps are involved in the process of visualizing data?',
                    'answer' => 'The process involves analyzing the type of data to be displayed, understanding the information that the observer wishes to extract or convey, and defining a mapping from the initial state of data to a form displayable to an observer.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What types of data might an observer find interesting in a visualization?',
                    'answer' => 'Observers may find anomalies, clusters, and trends in the data interesting as they indicate unexpected behavior, shared characteristics, or predictive patterns respectively.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the role of interactive controls in the visualization process?',
                    'answer' => 'Interactive controls allow users to customize the visualization by changing parameters, variables, and attributes, tailoring the visual output to their specific needs.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Describe the stages involved in the computer graphics rendering pipeline.',
                    'answer' => 'The stages include Modeling, Viewing, Clipping, Hidden Surface Removal, Projection, and Rendering, where a 3D model is created, viewed, clipped, projected onto a 2D plane, and rendered based on various factors like light sources and material properties.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does ray tracing differ from the traditional graphics rendering pipeline?',
                    'answer' => 'Ray tracing involves casting rays through a camera to determine visible surfaces, handling reflective, translucent, and speechured surfaces by generating secondary rays, and using algorithms for intersection, orientation, and combination, requiring intensive computational effort.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What does data modeling involve in the visualization pipeline?',
                    'answer' => 'Data modeling involves structuring the data to be visualized, ensuring data fields like name, type, range, and semantics are in a form that permits easy accessibility for rapid and efficient visualization.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Describe the Data to Visual Mappings stage in the visualization pipeline.',
                    'answer' => 'This stage maps data values to graphical objects or their attributes, involving prior mappings like scaling, filtering, shifting, sampling, or interpolating to prepare for scene or visualization mappings.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the role of Scene Parameter Setting in the visualization pipeline?',
                    'answer' => 'In this stage, users specify data-independent visualization attributes like color map selection, sound map selection, and lighting specifications, especially important for 3D visualizations.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the main focus of the Knowledge Discovery Pipeline?',
                    'answer' => 'The main focus is on processing data to produce a model rather than a graphics display, involving steps like data integration, cleaning, mining, and pattern evaluation to ascertain the model’s attributes.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does interactive visualization play a role in the Knowledge Discovery Pipeline?',
                    'answer' => 'Interactive visualizations can be employed at any stage of the pipeline, allowing for computational steering where manual intervention influences the outcome of an otherwise autonomous process.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why is it critical for visualizations to avoid ambiguities?',
                    'answer' => 'It is critical for visualizations to avoid ambiguities to ensure information is conveyed accurately and unambiguously, preventing incorrect conclusions from being drawn.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What visual property allows a target to stand out in a display?',
                    'answer' => 'A unique visual property, such as a distinct hue or shape, allows a target to stand out in a display by being different from the distractor objects.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is preattentive processing and why is it significant in visualization?',
                    'answer' => 'Preattentive processing is the detection of specific visual properties rapidly and accurately by the low-level visual system, significant for its ability to identify information with little effort.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does the human visual systems constant motion, like saccadic motion, affect perception of images?',
                    'answer' => 'The constant motion, such as saccadic motion, can cause the eye to "play tricks" on the observer, leading to perceptions of movement or additional elements in static images due to afterimages combined with this motion.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why should visualizations avoid using graphical attributes that interfere with the information being conveyed?',
                    'answer' => 'Visualizations should avoid such attributes to prevent hindering the accurate communication of numerical values or causing observer discomfort and confusion, ensuring the visualizations effectiveness.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Define visualisation in the context of data analysis.',
                    'answer' => 'Visualisation is the process of representing data through graphical means, such as charts or graphs, to communicate information clearly and effectively.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the primary purpose of using scatter plots in data visualisation?',
                    'answer' => 'Scatter plots are used to visualize the relationship between two variables, helping to identify correlations, trends, and outliers within the data.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Explain the significance of position as a visual variable in scatter plots.',
                    'answer' => 'Position is crucial as it determines the spatial arrangement of data points, maximizing the display space for clear communication of the relationships and patterns within the data.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why might a semi-logarithmic scale be used in scatter plots?',
                    'answer' => 'A semi-logarithmic scale is used to handle data with a wide range, allowing for better visualization of exponential relationships by spreading out clustered data points.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How do visual variables enhance the representation of data in scatter plots?',
                    'answer' => 'Visual variables such as color, size, and shape allow for the encoding of additional data dimensions, enriching the scatter plot with layers of information beyond the basic two variables.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What role does shape, or marks, play in data visualization?',
                    'answer' => 'Shapes, or marks, represent data in visual space, helping to categorize and differentiate data sets without relying on color or size, making them crucial for monochrome publications.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why is it important for marks used in plots to be sufficiently different?',
                    'answer' => 'Marks must be sufficiently different to ensure observers can easily discriminate between data sets, especially in print media where color differentiation may not be available.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is a bubble plot and what does it represent?',
                    'answer' => 'A bubble plot is a scatterplot variation where a third variable is represented by the size of the bubbles, often used to add additional dimensions to the data being visualized.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does brightness enhance data visualization?',
                    'answer' => 'Brightness, by varying intensity within a single color, allows for additional data differentiation without altering the size of marks, leveraging human sensitivity to light intensity.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How can color be used as a visual variable in data visualization?',
                    'answer' => 'Color can categorize and distinguish data through the use of a wide palette, effectively encoding information beyond mere shape or size, especially in rich, multi-dimensional datasets.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the significance of orientation as a visual variable?',
                    'answer' => 'Orientation, through directional markers like arrows, can represent vector fields or directional data, offering insights into flow directions, wind patterns, or gradients in a dataset.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Describe how texture can be utilized in data visualization.',
                    'answer' => 'Texture, through patterns or shading, differentiates data sets without color, ideal for grayscale publications or to convey additional dimensional attributes within the visualized data.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the role of motion in data visualization?',
                    'answer' => 'Motion attracts attention to changes or dynamic processes within a dataset, applicable in digital media to illustrate trends, temporal changes, or to highlight specific data points dynamically.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why must care be taken when using different markers in a plot?',
                    'answer' => 'Different markers must be comparable in size and easily distinguishable to prevent bias or misinterpretation, ensuring clear and unbiased data representation.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Explain the concept of proportional visual variables in visualization.',
                    'answer' => 'Proportional visual variables represent data magnitude directly, such as through marker size in bubble plots, enabling quantitative comparisons at a glance based on visual proportions.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What types of data require specialized forms of visualization like geospatial data streams?',
                    'answer' => 'Geospatial data streams require specialized forms of visualization.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the primary purpose of using maps for geospatial data visualization?',
                    'answer' => 'Maps are used for providing specific information about locations, general information about spatial locations, and comparing patterns in multiple maps for geospatial data visualization.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Name a visual variable that represents the size of individual symbols in geospatial data visualization.',
                    'answer' => 'Size is a visual variable that represents the size of individual symbols in geospatial data visualization.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does orientation serve as a visual variable in geospatial data visualization?',
                    'answer' => 'Orientation serves as a visual variable by representing the direction of individual symbols or patterns in lines and areas in geospatial data visualization.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What type of geospatial data visualization uses color shading applied to zones to highlight specific data?',
                    'answer' => 'Chloropleth maps use color shading applied to zones to highlight specific data in geospatial data visualization.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Describe the main difference between a heat map and a chloropleth map.',
                    'answer' => 'The main difference is that heat maps represent data without corresponding to geographical boundaries, unlike chloropleth maps which use predetermined zones.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the purpose of using hexagonal binning in geospatial data visualization?',
                    'answer' => 'Hexagonal binning is used to represent data in geographic locations with equidistant cells, providing an efficient packing and preserving data accuracy.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How do dot maps signify the presence of a datum in geospatial data visualization?',
                    'answer' => 'Dot maps use a dot to indicate the presence of a datum, where the location of the dot matches the geographical location of the data being represented.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What advantage do cluster maps offer in visualizing dense pockets of data points?',
                    'answer' => 'Cluster maps group dense pockets of data points into single points, either sized or labeled with the number of points, useful for interactive maps with zoom capabilities.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How do bubble maps differ from other geospatial data visualizations?',
                    'answer' => 'Bubble maps differ by simultaneously representing two variables using varying sizes and colors of bubbles to indicate different data attributes.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the unique characteristic of cartogram maps in geospatial data visualization?',
                    'answer' => 'Cartogram maps uniquely distort maps in relation to a mapping variable, often replacing attributes like land area or distance with the variable being represented.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why is the choice of color progression important in chloropleth maps?',
                    'answer' => 'The choice of color progression is important because it affects how dispersion in the data is visualized, utilizing the eye’s ability to sense changes for efficient visualization.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the main purpose of using a single hue color progression in geospatial visualizations?',
                    'answer' => 'A single hue color progression is used to visualize a single data type in a map, evolving from high intensity to low intensity of the same hue.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What does a bi-polar color progression signify in geospatial data visualization?',
                    'answer' => 'A bi-polar color progression signifies changes, usually in sign, of a dataset by progressing from one color through white to another, indicating negative to positive changes.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does a heat map differ from a chloropleth map in representing geospatial data?',
                    'answer' => 'Heat maps represent matrix data as colors without corresponding to geographical boundaries, unlike chloropleth maps which use predetermined zones.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is the major advantage of using hexagonal binning in geospatial visualizations?',
                    'answer' => 'The major advantage is the efficient dense packing and equidistant property of hexagonal cells, providing accuracy without using data extrapolation techniques.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Explain how bubble maps are used in geospatial data visualization.',
                    'answer' => 'Bubble maps represent two variables simultaneously by varying the size and color of bubbles to indicate different data points on the map.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What is a cartogram map, and how does it represent geospatial data?',
                    'answer' => 'A cartogram map represents data in a diagrammatic form where mapping variables like land area or distance are replaced or distorted in relation to the data, potentially altering the map’s shape.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does the use of color progressions affect the visualization of geospatial data?',
                    'answer' => 'Color progressions enhance information transfer by exploiting the eye’s ability to sense changes, but a poor choice can result in ineffective and aesthetically displeasing maps.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What are the potential disadvantages of using a heat map for geospatial data visualization?',
                    'answer' => 'Heat maps may compromise data accuracy due to algorithmic extrapolation creating a continuous fill of color, potentially leading to unreliable extrapolated values.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why might hexagonal binning be preferred over standard rectangle/square packing for geospatial data?',
                    'answer' => 'Hexagonal binning offers dense packing and equidistant properties, providing a more efficient and accurate representation of granular geospatial data points.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What challenge do dot maps face in geospatial data visualization?',
                    'answer' => 'Dot maps can face challenges with the density of points, potentially leading to solid color blocks that obliterate geographical relevance, necessitating larger resolution maps.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Describe a major advantage and disadvantage of using cluster maps for geospatial data.',
                    'answer' => 'Cluster maps preserve geographical data integrity while providing clear information about data variables, but require interactive applications for effectiveness, limiting deployment in printed media.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How do bubble maps handle the potential blocking of smaller bubbles?',
                    'answer' => 'Bubble maps counter potential blocking by choosing suitable color maps and placing smaller bubbles on top of larger ones, though it can still be difficult to visualize more than 3 or 4 colors.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What challenge does the cartogram map face in accurately representing geospatial data?',
                    'answer' => 'Cartogram maps can distort the map in relation to the data being represented, potentially diminishing the perceived significance of countries or regions at the edge of distortions.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'Why is it important to consider color blindness and dichromatic vision when visualizing geospatial data?',
                    'answer' => 'Considering color blindness and dichromatic vision ensures that the map is effective and accessible to all viewers, avoiding reliance on color distinctions that may not be perceivable to everyone.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'What considerations should be made when choosing color progressions for geospatial data visualization?',
                    'answer' => 'Considerations should include the limitation to five to seven colors, ensuring distinguishability for the viewer, and avoiding progressions that may be confusing or aesthetically displeasing when reproduced in black and white.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ],
                [
                    'topic_id' => $topicId,
                    'question' => 'How does geospatial data visualization help in understanding and exploring large data sets?',
                    'answer' => 'Geospatial data visualization helps by providing clear and efficient representations of data related to geographical locations, enabling the exploration of patterns, trends, and distributions within large data sets.',
                    'difficulty' => 'Easy',
                    'type' => 'speech',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $courseId,
                ]
            ];

            foreach ($questions as $question) {
                DB::table('questions')->insert([
                    'topic_id' => $question['topic_id'],
                    'question' => $question['question'],
                    'answer' => $question['answer'],
                    'image_url' => $question['image_url'] ?? null,
                    'video_id' => $question['video_id'] ?? null,
                    'difficulty' => $question['difficulty'],
                    'type' => $question['type'],
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'course_id' => $question['course_id'],
                ]);
            }
        }
    }
}
